#!/bin/bash
#
#SBATCH --job-name=AMD-test
#SBATCH --nodes=1
#SBATCH --gres=gpu:mi50:1
#SBATCH --cpus-per-task=4
#SBATCH --time=2:00:00
#SBATCH --mem=24GB
#SBATCH --mail-type=END,FAIL,TIME_LIMIT
#SBATCH --mail-user=songxia23@gmail.com

module purge

FOLDER_NAMES=$1

EXTRA=""
if [[ $# == 2 ]]
then
  EXTRA="--explicit_ds_config $2"
fi

singularity exec \
    --overlay ~/conda_envs/pytorch1.11-rocm4.5.2-25GB-500K.sqf:ro \
    /scratch/work/public/hudson/images/rocm4.5.2-ubuntu20.04.3.sif \
    bash -c "source /ext3/env.sh; export PYTHONPATH=../dataProviders:$PYTHONPATH; python test.py --folder_names '$FOLDER_NAMES' $EXTRA "
