data:
  data_provider: protein_embedding[dataset_name=casf2016-blind-screening-hetero/part_*.pyg]
  data_root: /scratch/sx801/data/im_datasets
  dataset_names: null
  pre_computed:
    atom_prop_ds: CASF-2016-BlindDockingScreening_ligmolprop_frag20sol_012_ens.allh.pyg
    lig_identifier_dst: file_handle
    lig_identifier_src: file_handle
    prot_embedding_root:
    - /CASF-2016-cyang/polar.esm2_t33_650M_UR50D
    rmsd_csv: /vast/sx801/geometries/CASF-2016-BlindDocking/screening/rmsd_info/chunk_*.csv
    nrot_csv: auto
record_name:
- sample_id
- file_handle
short_name: casf2016-blind-screening
training:
  valid_batch_size: 32
