data:
  data_provider: protein_embedding[dataset_name=merck.fep.hetero.mindist.pyg]
  data_root: /scratch/sx801/data/im_datasets
  pre_computed:
    atom_prop_ds: MerckFEP_ligmolprop_frag20sol_012_ens.allh.pyg
    lig_identifier_dst: file_handle
    lig_identifier_src: file_handle
    prot_embedding_root:
    - /vast/sx801/geometries/fep-benchmark/esm2_t33_650M_UR50D/
    rmsd_csv: /vast/sx801/geometries/fep-benchmark/rmsd_info.csv
record_name:
- sample_id
- file_handle
short_name: merck_fep
